/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SwapModule,
  SwapModuleInterface,
} from "../../../contracts/OneInchContract.sol/SwapModule";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "OK",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenToSwap",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "desiredToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountToSwap",
        type: "uint256",
      },
    ],
    name: "SwapTokenRequest",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenToSwap",
        type: "address",
      },
      {
        internalType: "address",
        name: "desiredToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountToSwap",
        type: "uint256",
      },
    ],
    name: "swapToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061037b806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80630c0a763014610030575b600080fd5b61004361003e366004610319565b610045565b005b6000826001600160a01b03166318160ddd6040518163ffffffff1660e01b8152600401602060405180830381865afa158015610085573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100a99190610355565b116100fb5760405162461bcd60e51b815260206004820152601560248201527f496e76616c69642064657369726564546f6b656e20000000000000000000000060448201526064015b60405180910390fd5b6000836001600160a01b03166318160ddd6040518163ffffffff1660e01b8152600401602060405180830381865afa15801561013b573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061015f9190610355565b116101ac5760405162461bcd60e51b815260206004820152601460248201527f496e76616c696420746f6b656e546f537761702000000000000000000000000060448201526064016100f2565b6040516370a0823160e01b815233600482015281906001600160a01b038516906370a0823190602401602060405180830381865afa1580156101f2573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906102169190610355565b10156102645760405162461bcd60e51b815260206004820181905260248201527f496e73756666696369656e7420746f6b656e546f537761702062616c616e636560448201526064016100f2565b816001600160a01b0316836001600160a01b0316036102ab576040517fd48fe2800bace8f5ca2450feacbd6efc681b1cd0115019bb49fa529b6171bf6790600090a1505050565b604080516001600160a01b0385811682528416602082015290810182905233907f9445469c0db898313ef8a39bf6d8ea931a0c9a40d5acabb17c867a80ed14f8979060600160405180910390a2505050565b80356001600160a01b038116811461031457600080fd5b919050565b60008060006060848603121561032e57600080fd5b610337846102fd565b9250610345602085016102fd565b9150604084013590509250925092565b60006020828403121561036757600080fd5b505191905056fea164736f6c6343000814000a";

type SwapModuleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SwapModuleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SwapModule__factory extends ContractFactory {
  constructor(...args: SwapModuleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SwapModule & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SwapModule__factory {
    return super.connect(runner) as SwapModule__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SwapModuleInterface {
    return new Interface(_abi) as SwapModuleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SwapModule {
    return new Contract(address, _abi, runner) as unknown as SwapModule;
  }
}
