[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
solc_version = '0.8.20'
evm_version = 'paris'
optimizer = true
optimizer_runs = 1000000