/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SafeModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeReceiverToken"
      | "checkSwapRequired"
      | "owner"
      | "ownerToken"
      | "receiverToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SwapRequired"): EventFragment;

  encodeFunctionData(
    functionFragment: "changeReceiverToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSwapRequired",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiverToken",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "changeReceiverToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSwapRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiverToken",
    data: BytesLike
  ): Result;
}

export namespace SwapRequiredEvent {
  export type InputTuple = [swapNeeded: boolean];
  export type OutputTuple = [swapNeeded: boolean];
  export interface OutputObject {
    swapNeeded: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafeModule extends BaseContract {
  connect(runner?: ContractRunner | null): SafeModule;
  waitForDeployment(): Promise<this>;

  interface: SafeModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeReceiverToken: TypedContractMethod<
    [_newReceiverTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  checkSwapRequired: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerToken: TypedContractMethod<[], [string], "view">;

  receiverToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeReceiverToken"
  ): TypedContractMethod<
    [_newReceiverTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkSwapRequired"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiverToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "SwapRequired"
  ): TypedContractEvent<
    SwapRequiredEvent.InputTuple,
    SwapRequiredEvent.OutputTuple,
    SwapRequiredEvent.OutputObject
  >;

  filters: {
    "SwapRequired(bool)": TypedContractEvent<
      SwapRequiredEvent.InputTuple,
      SwapRequiredEvent.OutputTuple,
      SwapRequiredEvent.OutputObject
    >;
    SwapRequired: TypedContractEvent<
      SwapRequiredEvent.InputTuple,
      SwapRequiredEvent.OutputTuple,
      SwapRequiredEvent.OutputObject
    >;
  };
}
