/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as oneInchContractSol from "./OneInchContract.sol";
export * as mockerc20Sol from "./mockerc20.sol";
export * as swapContractSol from "./swapContract.sol";
