/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fclWebauthnSol from "./FCL_Webauthn.sol";
export type { fclWebauthnSol };
import type * as fclEllipticSol from "./FCL_elliptic.sol";
export type { fclEllipticSol };
