/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockerc20Sol from "./mockerc20.sol";
export type { mockerc20Sol };
export type { Lock } from "./Lock";
export type { TokenSwap } from "./TokenSwap";
