/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oneInchContractSol from "./OneInchContract.sol";
export type { oneInchContractSol };
import type * as mockerc20Sol from "./mockerc20.sol";
export type { mockerc20Sol };
import type * as swapContractSol from "./swapContract.sol";
export type { swapContractSol };
